# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2026 Vipin Balakrishnan

# The filename and section name MUST match.
#
# resolvebox.ini
#       ↓
# [resolvebox]
#       ↓
# Distrobox name = resolvebox

[resolvebox]

image=localhost/resolvebox-amd:44

pull=false

root=false

init=false

nvidia=false

replace=false

start_now=true

entry=false

home=/mnt/mydata/documents/systemExternalDependency/distrobox-home/resolvebox

# ============================================================
# Optional custom HOME
# ============================================================

# Use an absolute HOST path.
#
# Example:
#
# home=/mnt/mydata/documents/systemExternalDependency/distrobox-home/resolvebox/


# ============================================================
# Optional mounts
# ============================================================

# Example:
#
# volume=/mnt/mydata/video:/mnt/video:rw